# batch config

label:          'Fales Willam Jones'
# description:    ''
attribution:    'NYU Libraries Special Collections'

presentation_api_url: 'https://aperitiiif-presentation-api-store.s3.us-east-1.amazonaws.com'
image_api_url:        'https://d1b7k5w7yjwpfg.cloudfront.net/iiif/2'

records:
  file: 'src/records.csv'
